Alias "/agent" "C:/xampp/htdocs/uisagent/public"
<Directory "C:/xampp/htdocs/uisagent/public">
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
    DirectoryIndex index.php
</Directory>
